services:
  - type: web
    name: hackops-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: ./server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: hackops-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: hackops-backend
          property: host